### ISSUE TITLE
iteritems

### ISSUE THREAD

**Issue by derVedro** [cynthia/pyflann3#4]
iteritems is removed from python3
#5

**Comment by cynthia** [comment]
Merged.

**Comment by derVedro** [comment]
by the way, some folks did a little work on porting pyflann to python3
https://github.com/ImmobilienScout24/pyflann
May be you should have a look at them?

I for myself used it a few times, it's "working" for searching, but stuff like save_index and load_index is broken.

**Comment by cynthia** [comment]
I'll take a look and see if there are any patches I should take in - I'd be willing to collaborate, but my main focus is a package that works out of the box with Intel accelerated libraries.

I'm curious if save/load is broken here as well. Haven't tested that as this is still WIP.
